services:
  # Base de Datos
  db:
    image: mysql:8.0
    container_name: mysql-turnos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestiondeturnos
      MYSQL_USER: Coder
      MYSQL_PASSWORD: Qwe.123*
    ports:
      - "3307:3306" # Mapeamos a 3307 en el host para no chocar con local
    volumes:
      - db-data:/var/lib/mysql
    dns:
      - 8.8.8.8

  # Aplicación Web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestor-turnos-app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:8080" # http: Mapeamos el puero 8080 del contenedor al 5000 del host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Conexión apuntando al servicio 'db' en lugar de localhost
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=gestiondeturnos;User=Coder;Password=Qwe.123*;AllowUserVariables=True;TreatTinyAsBoolean=true;
      - ASPNETCORE_URLS=http://+:8080
    dns:
      - 8.8.8.8

volumes:
  db-data:
